version: "3.9"

volumes:
  data:

services:
  acclab-app:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    container_name: acclab_app
    ports:
      - 3000:3000
    volumes:
    - .:/app
    - /app/node_modules
    restart: always