# pull official base image
FROM node:14-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

#Install App Dependencies
COPY package.json .
COPY yarn.lock .

RUN yarn install --frozen-lockfile
RUN yarn add @craco/craco

# add app
COPY . ./

# start app
CMD ["npm", "start"]