version: "3.9"

volumes:
  data:

services:
  acclab-app:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    
    #docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d --build