# pull official base image
FROM node:latest

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./

RUN apt-get update

RUN npm install -g npm@8.7.0
RUN yarn add @craco/craco

# add app
COPY . ./

EXPOSE 3000

# start app
CMD ["npm", "start"]